package com.example.clothesdb.models.enums

import androidx.room.ColumnInfo

enum class SubTypeEnumDBO {
    @ColumnInfo("tShirt")
    T_SHIRT,
    @ColumnInfo("sweater")
    SWEATER,
    @ColumnInfo("hoodie")
    HOODIE,
    @ColumnInfo("jacket")
    JACKET,
    @ColumnInfo("jeans")
    JEANS,
    @ColumnInfo("trousers")
    TROUSERS,
    @ColumnInfo("skirt")
    SKIRT,
    @ColumnInfo("dress")
    DRESS,
    @ColumnInfo("shoes")
    SHOES,
    @ColumnInfo("hat")
    HAT,
    @ColumnInfo("scarf")
    SCARF,
    @ColumnInfo("belt")
    BELT,
    @ColumnInfo("bag")
    BAG,
    @ColumnInfo("glasses")
    GLASSES,
    @ColumnInfo("socks")
    SOCKS,
    @ColumnInfo("underwear")
    UNDERWEAR,
    @ColumnInfo("swimsuit")
    SWIMSUIT,
    @ColumnInfo("pajamas")
    PAJAMAS,
    @ColumnInfo("shorts")
    SHORTS,
    @ColumnInfo("coat")
    COAT,
    @ColumnInfo("raincoat")
    RAINCOAT,
    @ColumnInfo("vest")
    VEST,
    @ColumnInfo("jumpsuit")
    JUMPSUIT,
    @ColumnInfo("romper")
    ROMPER,
    @ColumnInfo("blazer")
    BLAZER,
    @ColumnInfo("cardigan")
    CARDIGAN,
    @ColumnInfo("trenchCoat")
    TRENCH_COAT,
    @ColumnInfo("overall")
    OVERALL,
    @ColumnInfo("legging")
    LEGGING,
    @ColumnInfo("tights")
    TIGHTS,
    @ColumnInfo("gloves")
    GLOVES,
    @ColumnInfo("scarf")
    SCARF,
    @ColumnInfo("slippers")
    SLIPPERS,
    @ColumnInfo("sandals")
    SANDALS,
    @ColumnInfo("boots")
    BOOTS,
    @ColumnInfo("sneakers")
    SNEAKERS,
    @ColumnInfo("slippers")
    SLIPPERS,
    @ColumnInfo("moccasins")
    MOCASSINS,
    @ColumnInfo("loafers")
    LOAFERS,
    @ColumnInfo("balletFlats")
    BALLET_FLATS,
    @ColumnInfo("heels")
    HEELS,
    @ColumnInfo("flipFlops")
    FLIP_FLOPS,
    @ColumnInfo("espadrilles")
    ESPADRILLES


}
